#pragma once

#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME             "AUTOMATOUS.IO"
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME            "Shelly 1 Gen4 MoT Light"
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING "1.0.0"
