#pragma once

#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME             "AUTOMATOUS.IO"
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME            "Shelly 1 Mini Gen4 MoT Light"
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING "1.2.0"
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION        0x00010200
#define CHIP_DEVICE_CONFIG_DEFAULT_DEVICE_HARDWARE_VERSION_STRING "v0.1.0"
#define CHIP_DEVICE_CONFIG_DEVICE_HARDWARE_VERSION 0
#define CHIP_DEVICE_CONFIG_DEVICE_HARDWARE_VERSION_STRING "v0.1.0"